
game_dictionary = {'away': {'colors': ['Turquoise', 'Purple'],
  'players': {'Bismak Byombo': {'assists': 7,
    'blocks': 15,
    'number': 0,
    'points': 12,
    'rebounds': 4,
    'shoe': 16,
    'slam_dunks': 10,
    'steals': 7},
   'Jeff Adrien': {'assists': 1,
    'blocks': 7,
    'number': 4,
    'points': 10,
    'rebounds': 1,
    'shoe': 18,
    'slam_dunks': 2,
    'steals': 2},
   'player_name': {'assists': '',
    'blocks': '',
    'number': '',
    'points': '',
    'rebounds': '',
    'shoe': '',
    'slam_dunks': '',
    'steals': ''}},
  'team_name': 'Charlotte Hornets'},
 'home': {'colors': ['Black', 'White'],
  'players': {'Alan Anderson': {'assists': 12,
    'blocks': 1,
    'number': 0,
    'points': 22,
    'rebounds': 12,
    'shoe': 16,
    'slam_dunks': 1,
    'steals': 3},
   'Brook Lopez': {'assists': 10,
    'blocks': 1,
    'number': 11,
    'points': 17,
    'rebounds': 19,
    'shoe': 17,
    'slam_dunks': 15,
    'steals': 3},
   'Jason Terry': {'assists': 2,
    'blocks': 11,
    'number': 31,
    'points': 19,
    'rebounds': 2,
    'shoe': 15,
    'slam_dunks': 1,
    'steals': 4},
   'Mason Plumlee': {'assists': 6,
    'blocks': 8,
    'number': 1,
    'points': 26,
    'rebounds': 12,
    'shoe': 19,
    'slam_dunks': 5,
    'steals': 3},
   'Reggie Evans': {'assists': 12,
    'blocks': 12,
    'number': 30,
    'points': 12,
    'rebounds': 12,
    'shoe': 14,
    'slam_dunks': 7,
    'steals': 12}},
  'team_name': 'Brooklyn Nets'}}


game_dictionary['away']['players']['DeSagna Diop'] = 
{'number': 2, 'shoe': 14, 'points': 22, 'rebounds': 12, 'assists': 7, 'steals': 7 , 'blocks': 15 , 'slam_dunks': 10 }
#need to do Bismak Biyombo 